spring:
  datasource:
    url: jdbc:mysql://117.17.157.166:3306/ocean?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ocean
    password: ocean

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /resources/**
  
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
    
server:
  port: 8082

    