spring:
  datasource:
    url: jdbc:log4jdbc:mysql://database-1.cn0uid9h07ct.ap-northeast-2.rds.amazonaws.com:3306/blueOcean?serverTimezone=UTC
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    username: ocean
    password: ocean
    
  servlet:
    multipart:
      max-file-size: 10000MB
      max-request-size: 10000MB
        

  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp
    static-path-pattern: /resources/**
  
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false
    
server:
  port: 8082

logging:
  level:
    jdbc.sqlonly: DEBUG
  pattern:
    console: "[%d{HH:mm:ss.SSS}] [%thread{40}] %clr(%-5level) %clr(%logger{36}.%M:%L){cyan} | %msg%n%ex"
